name: oats
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.6
  - pandas
  - numpy
  - scikit-learn
  - jupyter
  - rdflib
  - sparqlwrapper
  - fuzzywuzzy
  - nltk
  - pronto=0.12.2
  - biopython
  - seaborn
  - networkx
  - scipy
  - flask
  - pip
  - pip:
    - pywsd==1.2.4
    - gensim==3.8.1
    - fastsemsim==1.0.0
    - pytorch-pretrained-bert==0.6.2
    - sphinx_bootstrap_theme
